-- 今天吃什么：Supabase/Postgres 数据结构
-- 在 Supabase Dashboard > SQL Editor 中完整执行一次。

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 50),
  code text not null unique check (char_length(code) between 3 and 32),
  created_at timestamptz not null default now()
);

create table if not exists public.foods (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  category text not null default '未分类',
  group_id bigint not null references public.groups(id) on delete cascade,
  updated_at timestamptz not null default now()
);

create table if not exists public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  token text not null check (char_length(token) between 1 and 120),
  name text not null check (char_length(name) between 1 and 30),
  joined_at timestamptz not null default now(),
  unique (group_id, token)
);

create table if not exists public.food_ratings (
  id bigint generated by default as identity primary key,
  food_id bigint not null references public.foods(id) on delete cascade,
  member_id bigint not null references public.group_members(id) on delete cascade,
  score integer not null check (score between 1 and 5),
  updated_at timestamptz not null default now(),
  unique (food_id, member_id)
);

create table if not exists public.food_visits (
  id bigint generated by default as identity primary key,
  food_id bigint not null references public.foods(id) on delete cascade,
  member_id bigint not null references public.group_members(id) on delete cascade,
  visited_at timestamptz not null default now()
);

create index if not exists foods_group_id_idx on public.foods(group_id);
create index if not exists group_members_group_id_idx on public.group_members(group_id);
create index if not exists group_members_token_idx on public.group_members(token);
create index if not exists food_ratings_food_id_idx on public.food_ratings(food_id);
create index if not exists food_ratings_member_id_idx on public.food_ratings(member_id);
create index if not exists food_visits_food_id_idx on public.food_visits(food_id);
create index if not exists food_visits_member_id_idx on public.food_visits(member_id);

-- 浏览器不能直接读写表；所有请求必须经过 Cloudflare Worker。
alter table public.groups enable row level security;
alter table public.foods enable row level security;
alter table public.group_members enable row level security;
alter table public.food_ratings enable row level security;
alter table public.food_visits enable row level security;

-- 以单个事务替换某个群的餐厅，避免导入过程中只删未写。
create or replace function public.replace_group_foods(
  p_group_id bigint,
  p_items jsonb
)
returns setof public.foods
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.foods where group_id = p_group_id;

  return query
  insert into public.foods (name, category, group_id)
  select
    item.name,
    coalesce(nullif(trim(item.category), ''), '未分类'),
    p_group_id
  from jsonb_to_recordset(p_items) as item(name text, category text)
  returning *;
end;
$$;

revoke all on function public.replace_group_foods(bigint, jsonb) from public, anon, authenticated;
grant execute on function public.replace_group_foods(bigint, jsonb) to service_role;

insert into public.groups (name, code)
values ('默认吃饭群', 'default')
on conflict (code) do nothing;

insert into public.foods (name, category, group_id)
select seed.name, seed.category, g.id
from public.groups g
cross join (
  values
    ('番茄鸡蛋盖浇饭', '主食'),
    ('番茄牛腩面', '面食'),
    ('酸辣土豆丝', '热菜'),
    ('清炒西蓝花', '素菜'),
    ('红烧排骨', '热菜'),
    ('麻婆豆腐', '热菜'),
    ('蛋炒饭', '主食')
) as seed(name, category)
where g.code = 'default'
  and not exists (
    select 1 from public.foods f where f.group_id = g.id
  );
