-- 今天吃什么：Supabase/Postgres 数据结构
-- 在 Supabase Dashboard > SQL Editor 中完整执行一次。

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 50),
  code text not null unique check (char_length(code) between 3 and 32),
  owner_id uuid references auth.users(id) on delete set null,
  is_personal boolean not null default false,
  distance_origin_name text,
  distance_origin_unit text not null default 'm',
  created_at timestamptz not null default now()
);

create table if not exists public.foods (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  category text not null default '未分类',
  group_id bigint not null references public.groups(id) on delete cascade,
  legacy_id text,
  avg_price_yuan integer check (avg_price_yuan is null or avg_price_yuan >= 0),
  distance_m integer check (distance_m is null or distance_m >= 0),
  location_label text check (location_label is null or char_length(location_label) <= 50),
  tags jsonb not null default '[]'::jsonb,
  enabled boolean not null default true,
  imported_confirmed_count integer not null default 0 check (imported_confirmed_count >= 0),
  source text not null default 'manual',
  source_created_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  token text check (char_length(token) between 1 and 120),
  name text not null check (char_length(name) between 1 and 30),
  role text not null default 'member',
  joined_at timestamptz not null default now(),
  unique (group_id, token),
  unique (group_id, user_id),
  constraint group_members_role_check check (role in ('owner', 'member')),
  constraint group_members_identity_check check (user_id is not null or token is not null)
);

create table if not exists public.food_ratings (
  id bigint generated by default as identity primary key,
  food_id bigint not null references public.foods(id) on delete cascade,
  member_id bigint not null references public.group_members(id) on delete cascade,
  score integer not null check (score between 1 and 5),
  updated_at timestamptz not null default now(),
  unique (food_id, member_id)
);

create table if not exists public.food_visits (
  id bigint generated by default as identity primary key,
  food_id bigint not null references public.foods(id) on delete cascade,
  member_id bigint not null references public.group_members(id) on delete cascade,
  visited_at timestamptz not null default now()
);

create table if not exists public.meal_picks (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  food_id bigint references public.foods(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  food_name text not null,
  category text not null default '未分类',
  picked_at timestamptz not null default now()
);

-- 兼容已部署的第一版表结构：重复执行本文件也能安全升级。
alter table public.groups
  add column if not exists owner_id uuid references auth.users(id) on delete set null;
alter table public.groups
  add column if not exists is_personal boolean not null default false;
alter table public.groups
  add column if not exists distance_origin_name text;
alter table public.groups
  add column if not exists distance_origin_unit text not null default 'm';

alter table public.foods add column if not exists legacy_id text;
alter table public.foods add column if not exists avg_price_yuan integer;
alter table public.foods add column if not exists distance_m integer;
alter table public.foods add column if not exists location_label text;
alter table public.foods add column if not exists tags jsonb not null default '[]'::jsonb;
alter table public.foods add column if not exists enabled boolean not null default true;
alter table public.foods add column if not exists imported_confirmed_count integer not null default 0;
alter table public.foods add column if not exists source text not null default 'manual';
alter table public.foods add column if not exists source_created_at timestamptz;

alter table public.group_members
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.group_members
  add column if not exists role text not null default 'member';
alter table public.group_members
  alter column token drop not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'group_members_group_id_user_id_key'
      and conrelid = 'public.group_members'::regclass
  ) then
    alter table public.group_members
      add constraint group_members_group_id_user_id_key unique (group_id, user_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'group_members_identity_check'
      and conrelid = 'public.group_members'::regclass
  ) then
    alter table public.group_members
      add constraint group_members_identity_check
      check (user_id is not null or token is not null) not valid;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'group_members_role_check'
      and conrelid = 'public.group_members'::regclass
  ) then
    alter table public.group_members
      add constraint group_members_role_check
      check (role in ('owner', 'member')) not valid;
  end if;
end $$;

create index if not exists foods_group_id_idx on public.foods(group_id);
create unique index if not exists groups_one_personal_per_owner_idx
  on public.groups(owner_id)
  where is_personal = true and owner_id is not null;
create index if not exists group_members_group_id_idx on public.group_members(group_id);
create index if not exists group_members_token_idx on public.group_members(token);
create index if not exists group_members_user_id_idx on public.group_members(user_id);
create index if not exists food_ratings_food_id_idx on public.food_ratings(food_id);
create index if not exists food_ratings_member_id_idx on public.food_ratings(member_id);
create index if not exists food_visits_food_id_idx on public.food_visits(food_id);
create index if not exists food_visits_member_id_idx on public.food_visits(member_id);
create index if not exists meal_picks_group_user_idx on public.meal_picks(group_id, user_id, picked_at desc);

-- 浏览器不能直接读写表；所有请求必须经过 Cloudflare Worker。
alter table public.groups enable row level security;
alter table public.foods enable row level security;
alter table public.group_members enable row level security;
alter table public.food_ratings enable row level security;
alter table public.food_visits enable row level security;
alter table public.meal_picks enable row level security;

-- 以单个事务替换某个群的餐厅，避免导入过程中只删未写。
create or replace function public.replace_group_foods(
  p_group_id bigint,
  p_items jsonb
)
returns setof public.foods
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.foods where group_id = p_group_id;

  return query
  insert into public.foods (name, category, group_id)
  select
    item.name,
    coalesce(nullif(trim(item.category), ''), '未分类'),
    p_group_id
  from jsonb_to_recordset(p_items) as item(name text, category text)
  returning *;
end;
$$;

revoke all on function public.replace_group_foods(bigint, jsonb) from public, anon, authenticated;
grant execute on function public.replace_group_foods(bigint, jsonb) to service_role;

-- 导入完整餐厅包：保留群和成员，仅替换该群餐厅及其从属记录。
create or replace function public.replace_group_restaurants(
  p_group_id bigint,
  p_items jsonb,
  p_origin_name text default null,
  p_origin_unit text default 'm'
)
returns setof public.foods
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.foods where group_id = p_group_id;

  update public.groups
  set distance_origin_name = nullif(trim(p_origin_name), ''),
      distance_origin_unit = coalesce(nullif(trim(p_origin_unit), ''), 'm')
  where id = p_group_id;

  return query
  insert into public.foods (
    name, category, group_id, legacy_id, avg_price_yuan, distance_m, location_label, tags,
    enabled, imported_confirmed_count, source, source_created_at
  )
  select
    item.name,
    coalesce(nullif(trim(item.category), ''), '未分类'),
    p_group_id,
    nullif(trim(item.legacy_id), ''),
    item.avg_price_yuan,
    item.distance_m,
    nullif(trim(item.location_label), ''),
    coalesce(item.tags, '[]'::jsonb),
    coalesce(item.enabled, true),
    coalesce(item.imported_confirmed_count, 0),
    coalesce(nullif(trim(item.source), ''), 'manual'),
    item.source_created_at
  from jsonb_to_recordset(p_items) as item(
    name text,
    category text,
    legacy_id text,
    avg_price_yuan integer,
    distance_m integer,
    location_label text,
    tags jsonb,
    enabled boolean,
    imported_confirmed_count integer,
    source text,
    source_created_at timestamptz
  )
  returning *;
end;
$$;

revoke all on function public.replace_group_restaurants(bigint, jsonb, text, text) from public, anon, authenticated;
grant execute on function public.replace_group_restaurants(bigint, jsonb, text, text) to service_role;

insert into public.groups (name, code)
values ('默认吃饭群', 'default')
on conflict (code) do nothing;

insert into public.foods (name, category, group_id)
select seed.name, seed.category, g.id
from public.groups g
cross join (
  values
    ('大米先生', '中式快餐'),
    ('乡村基', '中式快餐'),
    ('麦当劳', '西式快餐')
) as seed(name, category)
where g.code = 'default'
  and not exists (
    select 1 from public.foods f where f.group_id = g.id
  );
